SELECT P.PAYMENT_ID
FROM PAYMENTS P
WHERE NOT EXISTS (
    SELECT 1
    FROM PAYMENT_ATTEMPTS A
    WHERE P.PAYMENT_ID = A.PAYMENT_ID
      AND A.STATUS = 'SUCCESS'
      AND A.PAYMENT_DATE <= P.SCHEDULED_DATE
)
ORDER BY P.PAYMENT_ID DESC;