-- 기출 5. 결제 실패 조회 (SQL)
-- 소요시간: 7분 / 시도: 1회

-- 예정일 당일까지 SUCCESS한 시도가 하나도 없으면 실패
SELECT P.PAYMENT_ID
FROM PAYMENTS P
WHERE NOT EXISTS (
    SELECT 1
    FROM PAYMENT_ATTEMPTS A
    WHERE A.PAYMENT_ID = P.PAYMENT_ID
      AND A.STATUS = 'SUCCESS'
      AND A.PAYMENT_DATE <= P.SCHEDULED_DATE
)
ORDER BY P.PAYMENT_ID DESC;
