# 최대조개수
# 소요시간 : 7분

SELECT LEAST(
    COUNT(CASE WHEN PROGRAMMING_LANGUAGE = 'C++' THEN 1 END),
    COUNT(CASE WHEN PROGRAMMING_LANGUAGE = 'C' THEN 1 END),
    COUNT(CASE WHEN PROGRAMMING_LANGUAGE = 'JAVA' THEN 1 END),
    COUNT(CASE WHEN PROGRAMMING_LANGUAGE = 'PYTHON' THEN 1 END),
    COUNT(CASE WHEN PROGRAMMING_LANGUAGE = 'C#' THEN 1 END)
) AS MAX_GROUP_COUNT
FROM APPLICANTS;